### ISSUE TITLE
Angaben im ER

### ISSUE THREAD

**Issue by zonky2** [Contao-DD/contao-advanced-classes#1]
Im ER geht der Link zum Forum auf die geschützte Seite http://gondao.de/

was ich im Forum geschrieben hätte: soll das Tool auch andere CSS.Klassen außer den Grid-Angaben aufnehmen? Wenn nein, wäre das Wort "Grid" im Namen sicher passender...

Gruss

**Comment by MDevster** [comment]
Hi,
der Link geht auf die neue sächsische Contao Stammtisch-Seite von Dresden, an dieser wird aber noch gearbeitet.

Zukünftig soll die Erweiterung diverse Sets, nicht nur für Bootstrap zur Verfügung stellen, daher der neutrale Name.
Wir planen auch einen kleinen Konfigurator auf der Stammtischseite um eigene Sets zu erstellen bzw. vorhandene zu bearbeiten.

Beim final wird der Text im ER natürlich noch etwas ausformuliert :)
Grüße

**Comment by zonky2** [comment]
`Erweiterung diverse Sets` - also doch (nur) Grids?

**Comment by MDevster** [comment]
Set steht nur stellvertretend für eine Sammlung von CSS-Klassen die gruppiert und frei definiert werden können.

**Comment by zonky2** [comment]
o.k.! bin gespannt...
