### ISSUE TITLE
Contao 4 Anpassungen

### ISSUE THREAD

**Issue by IdeeAnhang** [Contao-DD/contao-advanced-classes#11]
Mit ein paar kleinen Anpassungen ist das Plugin auch für Contao 4 nutzbar.
Durch Anpassung der Paletten zur Anzeige in Settings, Content und Module ist die Auswahl der CSS Klassen verfügbar. 
Angepasst sollte auch die Einbindung von jQuery werden.

**Comment by MDevster** [comment]
Über die Konsole ist es bereits zu installieren https://github.com/Contao-DD/advanced-classes-bundle
Bisher fehlt nur die Markierung das es auch für den Manager verfügbar ist.

**Comment by IdeeAnhang** [comment]
Ah ja dann schaut die Sache schon anders aus. Danke
