### ISSUE TITLE
Beschreibung aktualisieren

### ISSUE THREAD

**Issue by Olli** [Contao-DD/contao-advanced-classes#12]
Hi,
ich weiß ja nicht warum aber bei Contao Paketen wird oft an der Beschreibung der Funktionalität gespart.
Wäre es möglich das: 

> 
>  Contao Advanced Classes
> 
> Das Modul erweitert die CSS-Klassen der Contao Elemente durch selbst definierbare Sets an CSS-Klassen. Redakteure und Admins können über Select-Felder schnell auf vordefinierte CSS-Klassen zugreifen.
> 
> Über unseren Konfigurator (noch in der Entwicklung) lassen sich die Sets auf einfache Weise an eure Anforderungen anpassen.
> 
> Für Bootstrap wird bereits ein vordefiniertes Set für Spaltenbreite, Spalten-Offset, Reihenfolge (Pull/Push) und Sichtbarkeit mitgeliefert.

einfach in die Readme/Paketbeschreibung einzubauen?

**Comment by MDevster** [comment]
@seibtph Bitte auch hier ändern https://github.com/Contao-DD/advanced-classes-bundle/blob/master/README.md

Am besten die deutsche Beschreibung über About einfügen.

**Comment by seibtph** [comment]
Angepasst
