### ISSUE TITLE
Funktioniert nicht für Inhaltselement "Modul"

### ISSUE THREAD

**Issue by thepixture** [Contao-DD/contao-advanced-classes#3]
Wenn man ein Modul als Inhaltselement einbindet, dann werden die ausgwählten Klassen nicht im Frontend mit ausgegeben.

**Comment by MDevster** [comment]
Das werde ich die Tage noch mit einbauen :)

**Comment by visionpixel** [comment]
Ist nun integriert. Ebenso der Support bei Modulen, die das Feld "space" beinhalten. Bitte mal schauen ob dir das so reicht.
