### ISSUE TITLE
vorhandenes Feld für CSS-Klassen verwenden

### ISSUE THREAD

**Issue by thepixture** [Contao-DD/contao-advanced-classes#4]
Wenn das vorhandene Feld "ctrl_cssID_1" für die Auswahl verwendet wird, an Stelle des hidden "ctrl_advancedCss" Feldes, dann sollte es automatisch für alle Inhaltselemente funktionieren, auch für die Inhaltselemente der 3rd party Erweiterungen.

**Comment by MDevster** [comment]
Der Nachteil ist aber das wir das Feld dann nicht ausblenden können und das Standard-Feld bei vielen Klassen sehr unübersichtlich wird. Vote?

**Comment by MDevster** [comment]
Besser wäre es noch das Erweiterte CSS Feld auch wie die normalen CSS Klassen in Contao zu vererben, also auch bei Modulen mit durchzureichen. Fehlende Module können wir auf einfache Weise ergänzen indem wir vorher prüfen welche Module geladen sind und bei Bedarf die "Erweiterte Klasse" anhängen. Obwohl die Variante direkt die Contao CSS Klassen zu verwenden weniger Aufwand bedeutet... mmhhh. Was sagst du @visionpixel ?

**Comment by plixus** [comment]
Gibt's hier schon eine Lösung? Würde advanced_classes gern auch für dma_eg/rocksolid-custom-elements, eigene Inhaltselemente oder weitere 3rd party Erweiterungen nutzen. 
Kann mir da wer sagen wie?

**Comment by MDevster** [comment]
@visionpixel ping ;)

**Comment by MDevster** [comment]
Eigene Sets können ab Version 0.4.0 Beispielsweise über die localconfig.php hinzugefügt werden.
Beispiel: $GLOBALS['TL_CONFIG']['advancedClassesSets'][] = '/files/theme/myCssSet.json';

**Comment by operatorone** [comment]
Ist der Konfigurator für die Sets schon verfügbar?

**Comment by MDevster** [comment]
Nein, leider wurde dieser nicht weiter entwickelt. Wir verwenden derzeit Json Online Editoren wie [den hier](https://jsoneditoronline.org/?id=c6ab4bee600d41e2abce9fb8a30b6621)
um neue Sets zu erstellen.

**Comment by operatorone** [comment]
Danke für den Tipp. Den Editor schaue ich mir mal an.
