### ISSUE TITLE
 Default Wert für Option "Spaltenbreiten festlegen"

### ISSUE THREAD

**Issue by MDevster** [Contao-DD/contao-advanced-classes#5]
Was haltet ihr davon einen Default Wert für Option "Spaltenbreiten festlegen" zu definieren, beispielsweise auf 12 Spalten?

**Comment by thepixture** [comment]
fänd ich gut. hab ich sonst über die dca_config.php gelöst

**Comment by seibtph** [comment]
In 0.4.0 verfügbar.
