### ISSUE TITLE
Darstellung nach dem kopieren eines Inhaltselements

### ISSUE THREAD

**Issue by ideefixx** [Contao-DD/contao-advanced-classes#7]
Darstellung nach dem kopieren eines Inhaltselements gestört, lässt sich jedoch mittels max-width (advanced_classes/assets/css/advanced_classes.css) wie folgt beheben: 
# advancedFormContainer .ac-w20 {

```
width: 19%;
**max-width: 19%;**
float: left;
```

}
# advancedFormContainer .ac-w25 {

```
width: 24%;
**max-width: 24%;**
float: left;
```

}
# advancedFormContainer .ac-w33 {

```
width: 31% !important;
**max-width: 31% !important;**
float: left;
```

}
# advancedFormContainer .ac-w50 {

```
width: 49%;
**max-width: 49%;**
float: left;
```

}

**Comment by seibtph** [comment]
Scheint schon behoben zu sein. Tritt bei mir nicht mehr auf.

**Comment by seibtph** [comment]
war doch noch nicht behoben - behoben in 0.4.1
