### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by Metis77** [Contao-DD/contao-advanced-classes#8]
es sollte noch ein json mit den neuen bootstrap 4 Klassen geben.
(wie ich sehe, ist dies hier schon enthalten, aber noch mit den alten klassenamen. neu heißt es zB .push-xs-2)

**Comment by seibtph** [comment]
Wird in Version 0.4.0 enthalten sein. Das Bootstrap 4 Set ist die Beta-Version, die Alpha-Version wird es auch als Set geben.
