### ISSUE TITLE
json update save

### ISSUE THREAD

**Issue by Metis77** [Contao-DD/contao-advanced-classes#9]
könnte man das json file nicht auch in den Templates Ordner per contao "layout -> templates" kopieren und damit dort wählbar machen.
Damit würde das update sicher werden

**Comment by MDevster** [comment]
will be available in version 0.4.0
add update save json files via own extension or use default localconfig.php file
like $GLOBALS['TL_CONFIG']['advancedClassesSets'][] = '/files/theme/myCssSet.json';
